spring.application.name=Symptom-Advicer

# =========================
# PostgreSQL Database
# =========================
spring.datasource.url=jdbc:postgresql://dpg-d3179td6ubrc73c5rh5g-a:5432/symptom_advicer_check
spring.datasource.username=symptom_advicer_check_user
spring.datasource.password=Zl82NRQQEheVfAyhIjX4A8ZtIYVkfntI
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / Hibernate
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.sql.init.mode=always

# =========================
# Logging
# =========================
logging.level.org.springframework=DEBUG

# =========================
# JWT Config
# =========================
app.jwt-secret=MySecretKeywertyuiopasdfghjklxcvbnmsdfghjkertyuidfg
app.jwt-expiration-milliseconds=3600000
